### ISSUE TITLE
This setup procedure seems to be outdated

### ISSUE THREAD

**Issue by RamiMustaklem** [DivanteLtd/woocommerce2vuestorefront#2]
When running `yarn restore`

{ _index: 'vue_storefront_catalog_temp',
  _type: 'cms_block',
  _id: '3',
  status: 400,
  error:
   { type: 'illegal_argument_exception',
     reason: 'Rejecting mapping update to [vue_storefront_catalog_temp] as the final mapping would have more than 1 type: [cms_block, product]' } }

When running `yarn migrate`

Elasticsearch DEBUG: 2019-03-14T16:53:16Z
  Request complete

(node:16407) UnhandledPromiseRejectionWarning: Error: [illegal_argument_exception] Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type: [product, taxrule] :: {"path":"/vue_storefront_catalog/_mapping/taxrule","query":{},"body":"{\"properties\":{\"id\":{\"type\":\"long\"},\"rates\":{\"properties\":{\"rate\":{\"type\":\"float\"}}}}}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type: [product, taxrule]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type: [product, taxrule]\"},\"status\":400}"}
    at db.indices.putMapping.then.catch.err2 (/Users/ramimustaklem/Sites/vue-storefront-api/src/lib/elastic.js:177:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:16407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16407) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by eph6666** [comment]
same question, do you have any solution?
